{'name': 'Studio customizations',
 'version': '19.0.1.0',
 'category': 'Studio',
 'description': 'This module has been generated by Odoo Studio.\n'
                'It contains the apps created with Studio and the '
                'customizations of existing apps.',
 'author': 'GL Ecologie B.V.',
 'depends': ['web_studio'],
 'data': [],
 'demo': [],
 'license': 'OPL-1'}